// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmiIi0enhQWow2bOB15tZ6MzvKP0Bt28s',
    appId: '1:793717339647:web:9567c9a11d19b9eabc23ca',
    messagingSenderId: '793717339647',
    projectId: 'carelink-8d29a',
    authDomain: 'carelink-8d29a.firebaseapp.com',
    storageBucket: 'carelink-8d29a.appspot.com',
    measurementId: 'G-WYBREKK8DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv3QiYA2ao05YQdnLFJLUYZjyS_zshutA',
    appId: '1:793717339647:android:a86ea91c16077affbc23ca',
    messagingSenderId: '793717339647',
    projectId: 'carelink-8d29a',
    storageBucket: 'carelink-8d29a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0iKs1cl1Wq1l3XIevS3BG1u5rVGexQsY',
    appId: '1:793717339647:ios:f117103cb7372785bc23ca',
    messagingSenderId: '793717339647',
    projectId: 'carelink-8d29a',
    storageBucket: 'carelink-8d29a.appspot.com',
    iosBundleId: 'com.example.careLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0iKs1cl1Wq1l3XIevS3BG1u5rVGexQsY',
    appId: '1:793717339647:ios:2eb545213c1f8c13bc23ca',
    messagingSenderId: '793717339647',
    projectId: 'carelink-8d29a',
    storageBucket: 'carelink-8d29a.appspot.com',
    iosBundleId: 'com.example.careLink.RunnerTests',
  );
}
